### ISSUE TITLE
Add library to official Library Manager

### ISSUE THREAD

**Issue by schinken** [schinken/Flash#2]

**Comment by mvhconsult** [comment]
This seems to only require opening an issue at arduino, following https://www.arduino.cc/en/Guide/Libraries#toc3

eg https://github.com/arduino/Arduino/issues/5213
Need to fix issue #3 first, adding the required files.

**Comment by schinken** [comment]
Suggestion for library.properties:

```
name=Flash
version=1.0
author=Mikal Hart <mikal.n.hart@intel.com>
maintainer=Christopher Schirner <schinken@bamberg.ccc.de>, Michel V <mvhconsult@users.noreply.github.com>
sentence=A library to wrap accessing and writing to flash
category=Data Storage
url=http://github.com/schinken/Flash
architectures=avr
includes=Flash.h
```

@mvhconsult Do you want to publish your real mailaddress here?
@nohorbee I need some details if you want to be listed at "maintainer"

**Comment by mvhconsult** [comment]
I'm ok with you as maintainer. I am currently not actively using this library, but don't mind doing some docs and upgrades.
On the content: is it truly AVR limited, or could it work wider?

**Comment by schinken** [comment]
About the AVR stuff: I actually don't know, but I know it works on AVR :)

**Comment by mvhconsult** [comment]
ok, so let's be safe for now, until someone can test other hardware

**Comment by nohorbee** [comment]
Sure, which details would you need?

## 

_Norberto L. Herz_
[image: https://www.linkedin.com/pub/norberto-herz/5/887/177]
https://www.linkedin.com/pub/norberto-herz/5/887/177
https://twitter.com/nohorbee   https://www.facebook.com/nohorbee
*"Peace cannot be kept by force. It only can be achieved by understanding"
- Albert Einstein*

**Comment by mvhconsult** [comment]
Another resource https://github.com/arduino/Arduino/wiki/Library-Manager-FAQ

**Comment by schinken** [comment]
Opened issue: https://github.com/arduino/Arduino/issues/5229

**Comment by mvhconsult** [comment]
Congrats!

**Comment by schinken** [comment]
Added :)
