### ISSUE TITLE
Pull requests vs. directly commiting

### ISSUE THREAD

**Issue by schinken** [schinken/Flash#4]
@mvhconsult, @nohorbee: What do you think? Directly committing to repository or doing everything with a pull request?

**Comment by mvhconsult** [comment]
The advantage of pull requests is a good decision tree and checks. But it also means you will be in charge of merging ;). For the moment we can commit directly, but it would be nice to know that we are not doing double work. So I would suggest that you can submit directly _if_ you have been working on a reported issue that was assigned to you.
We can always change later if that moves us into troubles.

**Comment by nohorbee** [comment]
I think that pull requests are fine, as far as the merger is coming from a
pool and not a responsibility of a single person. And of course, if I'm
doing the pull request, I should not merge ;)

## 

_Norberto L. Herz_
[image: https://www.linkedin.com/pub/norberto-herz/5/887/177]
https://www.linkedin.com/pub/norberto-herz/5/887/177
https://twitter.com/nohorbee   https://www.facebook.com/nohorbee
*"Peace cannot be kept by force. It only can be achieved by understanding"
- Albert Einstein*

**Comment by schinken** [comment]
I did some commits directly for moving files etc. But for future changes I want to stay with the pull-request changes. I'm closing this issue, to bring down the counter ;)
