### ISSUE TITLE
Move files to root

### ISSUE THREAD

**Issue by mvhconsult** [schinken/Flash#9]
From the FAQ:

Is my git repo ok?

Your repo is ok if its root folder contains file library.properties and the rest of the library source code. If your library is stored into a subfolder, your repo it's not ok and we can't include your library in the list.

So the files should not be in /Flash but in /. I vote for /src as well, as we want 1.5+ compatibility. 

PS: sorry, should have seen it when merging the pull request.

**Comment by schinken** [comment]
Oh thanks for the info. I totally understood that wrong from the docs. That's why I created the subfolder. Going to move that back. Dang ;)
